default_language_version:
  python: python3
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml

-   repo: https://github.com/MarcoGorelli/cython-lint
    rev: v0.15.0
    hooks:
    -   id: cython-lint
    -   id: double-quote-cython-strings

-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        exclude: ^docs/

-   repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
    -   id: black
        exclude: ^docs/

-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        exclude: ^docs/

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.0
    hooks:
    -   id: mypy
        exclude: ^docs/

-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: python
        types: [python]
        require_serial: true


-   repo: local
    hooks:
    -   id: pytest-check
        name: pytest-check
        stages: [commit]
        types: [python]
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true