parameter_specificatie:
  Laonome calida: 'Laonome'
  Pseudocuma longicornis: 'Pseudocuma'
  Ensis directus: 'Ensis leei'
  Podarkeopsis helgolandica: 'Podarkeopsis'
  Pontocrates arcticus: 'Pontocrates'
  Goniadella bobretzkii: 'Goniadella'
  Hygrobates fluviatilis: "Hygrobates fluviatilis [1]"
  Hygrobates longipalpis: Hygrobates longipalpis [1]
  Einfeldia carbonaria/dissidens: Benthalia
 
